[project]
name = "pyclass"
version = "0.1.0"
description = "Advanced and scientific Python"
authors = ["Xavier Olive <git@xoolive.org>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.12"
numpy = "*"
scipy = "*"
matplotlib-base = "*"
jupyter = "*"
jupyterlab = "*"
pandas = "*"
scikit-learn = "*"
requests = "*"
tqdm = "*"
cartopy = "*"
shapely = "*"
aiohttp = "*"
rich = "*"
vpython = "*"
networkx = "*"
pygraphviz = "*"
skyfield = "*"
zeep = "*"
traffic = "*"
flask = "*"
flask_cors = "*"
textual = "*"
waitress = "*"
ruff = "*"
mypy = "*"
pandas-stubs = "*"
fiona = ">=1.10.1,<1.11"
geopandas = ">=1.0.1,<1.1"
libgfortran5 = ">=15.1.0,<16"
libopenblas = ">=0.3.30,<0.4"
